#!/usr/bin/env python3
# Generate soh/soh/z_staff_CHI.cpp : embedded staff credits as C++ arrays (method B).
# English placeholder data extracted from x64/Release/oot.o2r staff_message_data_static,
# used to verify the embedded C++ array loading path for CHI-language credits.
import zipfile, struct, os

ROOT = r"E:\Desktop\Shipwright-CN-cn-full"
OTR = os.path.join(ROOT, "x64", "Release", "oot.o2r")
OUT = os.path.join(ROOT, "soh", "soh", "z_staff_CHI.cpp")

z = zipfile.ZipFile(OTR)
data = z.read("text/staff_message_data_static/staff_message_data_static")

count = struct.unpack("<I", data[64:68])[0]
pos = 68
entries = []
for i in range(count):
    eid = struct.unpack("<H", data[pos:pos+2])[0]
    typePos = data[pos+2]
    msgSize = struct.unpack("<I", data[pos+4:pos+8])[0]
    msg = data[pos+8:pos+8+msgSize]
    entries.append((eid, typePos, msgSize, msg))
    pos += 8 + msgSize
assert pos == len(data), (pos, len(data))

real = [(eid, tp, sz, m) for (eid, tp, sz, m) in entries if eid != 0xFFFF]
print("real messages:", len(real), "ids:", [f"0x{e:#06x}" for e,_,_,_ in real[:3]], "...", f"0x{real[-1][0]:#06x}")

def fmt_bytes(b):
    out = []
    for i in range(0, len(b), 16):
        chunk = b[i:i+16]
        out.append("    " + ", ".join(f"0x{x:02X}" for x in chunk) + ",")
    return "\n".join(out).rstrip(",")

buf = []
buf.append("// Auto-generated by scripts/chinese/message/generate_staff_chi.py")
buf.append("// Method B verification: staff credits embedded as C++ arrays.")
buf.append("// Current content is ENGLISH (copied verbatim from oot.o2r staff_message_data_static)")
buf.append("// so the loading/decoding path can be verified. Replace these arrays with")
buf.append("// translated Chinese text later (keep ids/typePos; typePos stays 0x0B).")
buf.append("#include \"global.h\"")
buf.append("#include \"message_data_static.h\"")
buf.append("")
buf.append("// #region SOH [Chinese] - Embedded staff credits (method B)")
buf.append("")

for eid, tp, sz, m in real:
    buf.append(f"static const u8 sStaffCHIMsgData_{eid:04X}[] = {{")
    buf.append(fmt_bytes(m))
    buf.append("};")
    buf.append("")

buf.append("static MessageTableEntry sChiStaffMessageTable[] = {")
for eid, tp, sz, m in real:
    buf.append(f"    {{ 0x{eid:04X}, 0x{tp:02X}, (const char*)sStaffCHIMsgData_{eid:04X}, {sz} }},")
buf.append("    { 0xFFFF, 0x00, NULL, 0 },")
buf.append("};")
buf.append("")
buf.append("// Pointer referenced by z_message_PAL.c (Message_FindCreditsMessage) for CHI-language credits.")
buf.append("extern \"C\" MessageTableEntry* sChiStaffMessageEntryTablePtr = sChiStaffMessageTable;")
buf.append("")
buf.append("// #endregion")
buf.append("")

open(OUT, "w", encoding="utf-8").write("\n".join(buf))
print("WROTE", OUT, "bytes", os.path.getsize(OUT))
